# Menu 
menu:
  Home: /
  Archives: /archives
  測試: /#

rss: /atom.xml

# If setting available for using css function, 
# please DO NOT ADD character `;` in last word.

# Title Settings (using css function)
title_text: Modern Siberia
title_text_color: "#4d4d4d"
title_text_font: "Artegra Sans Alt"

#Bio Settings (using css function)
bio: Do my best so I can't blame my self for anything.
bio_text_color: "#0061b5"
bio_text_font: "PT Serif"

#Banner Settings(using css function)
avator_image: /avator.jpg #Default Photo Made by Krysten Merriman (https://www.pexels.com/photo/cat-whiskers-kitty-tabby-20787/)
avator_image_position_x: "-31px"
avator_image_position_y: "0px"
circle_color: rgba(83, 207, 220, 0.7)
banner: "url(/background/blur-cars-dew-125510.jpg)" #Default Photo Made by Kaique Rocha (https://www.pexels.com/photo/blur-cars-dew-drops-125510/)
banner_filter: "blur(2px) grayscale(20%)"
banner_mask_color: "#ffffff"
banner_mask_opacity: 0

#Body color (using css function)
theme_style: "#f2f2f2"
footer_style: "#151719"
footer_text_color: "#8a8a8a"

#Article Reading Style (using css function)
article_text_size: "19px"

article_text_color: "#151717"

article_link_color: "#29bcd0"

article_text_font: "source-han-serif-tc"
article_title_font: "source-han-serif-tc"
article_default_font: Helvetica Neue, Helvetica, Microsoft JhengHei , Arial, sans-serif

#Layout Setting (using css function)
prev_next_button_color_hover: "#151719"
prev_next_text_color: "#151719"
prev_next_text_color_hover: white

#Feature
mathjax_enable: true



#Read More Button Text
excerpt_link: Read More

#Feature Tags Translate (Only shows in one Language)
ftags:
  china_culture: 中國文化
  goods: 精選內容


# Miscellaneous
google_analytics:
favicon: /favicon.png